### ISSUE TITLE
Hallucinations in the teach() program. 

### ISSUE THREAD

**Issue by jdriscoll98** [paralleldrive/sudolang-llm-support#2]
I started using the teach() command and it did fine for lessons that were in the specification. However, after I finished "level 2" , it got confused and thought I was on "level 1". I tried to get it back on track but it started teaching me javascript but calling it SudoLang. 

Maybe the teach program should be a bit more restrained, and once it reaches beyond what's in the specification, have it exit the teach() program and enter some sort of "playground" where the user can learn by doing. 

Edit: Amazing repo btw

**Comment by jdriscoll98** [comment]
Side node: anyone building anything with langchain + sudolang?

**Comment by ericelliott** [comment]
Thanks for the report. Which language model were you using?

Simple SudoLang programs sometimes kinda work in GPT-3.5, but GPT-4 works much better.

Also, sometimes LLMs just get confused and you need to start a new session. This is technology in its infancy, and because of that, all SudoLang programs are inherently unpredictable and will make occasional mistakes, even with GPT-4.

Yes, people are building things with Langchain and SudoLang.
